# -*- coding: utf-8 -*-
"""CUSTOMER TRANSACTION DATA.PY

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1limqx-5h54TiiOycT2K2XT9rjC540mIs
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# TASK 1: Generate a synthetic dataset of at least 1000 rows
np.random.seed(42)
n_rows = 1000
categories = ['Electronics', 'Groceries', 'Clothing', 'Home', 'Books', 'Beauty']

data = {
    'CustomerID': np.random.randint(100, 999, n_rows),
    'Age': np.random.randint(18, 70, n_rows),
    'PurchaseAmount': np.random.uniform(10.0, 500.0, n_rows),
    'ProductCategory': np.random.choice(categories, n_rows),
    'TransactionDate': pd.to_datetime('2025-01-01') + pd.to_timedelta(np.random.randint(0, 365, n_rows), unit='d')
}

df = pd.DataFrame(data)

# Injecting some missing values for Task 2
df.loc[np.random.choice(df.index, 20), 'PurchaseAmount'] = np.nan

# TASK 2: Initial Data Inspection and Cleaning
print("--- Data Inspection ---")
print(df.info())  # Check data types and row/column counts

# Handling missing values: Using median imputation
# Decision: Imputing with median because PurchaseAmount can have outliers.
df['PurchaseAmount'] = df['PurchaseAmount'].fillna(df['PurchaseAmount'].median())
print(f"\nMissing values after cleaning: {df.isnull().sum().sum()}")

# TASK 3: Key Descriptive Statistics
print("\n--- Descriptive Statistics (Numerical) ---")
stats = df[['Age', 'PurchaseAmount']].agg(['mean', 'median', 'std'])
print(stats)

print("\n--- Frequency Counts (Top 5 Categories) ---")
print(df['ProductCategory'].value_counts().head(5))

# TASK 4: Visualizations
plt.figure(figsize=(15, 5))

# 1. Histogram for a numerical feature
plt.subplot(1, 3, 1)
sns.histplot(df['PurchaseAmount'], bins=30, kde=True, color='skyblue')
plt.title('Distribution of Purchase Amounts')

# 2. Bar chart for categorical distribution
plt.subplot(1, 3, 2)
df['ProductCategory'].value_counts().plot(kind='bar', color='salmon')
plt.title('Transactions per Category')
plt.xticks(rotation=45)

# 3. Box plot showing relationship between two variables
plt.subplot(1, 3, 3)
sns.boxplot(data=df, x='ProductCategory', y='Age')
plt.title('Age Distribution by Category')
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()